name: Quiz Checker

on:
  pull_request:
    types: [ opened, labeled, synchronize ]

jobs:
  check-quizzes:
    if: github.event.label.name == 'check_theory'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Check Quiz Answers
        id: quiz-check
        run: |
          python .github/scripts/check_quizzes.py

      - name: Ensure quiz_results.md is updated
        run: |
          # Add any command here to ensure the file is updated
          cat quiz_results.md

      - name: Add Results as PR Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const resultsPath = 'quiz_results.md';
            
            if (fs.existsSync(resultsPath)) {
              const results = fs.readFileSync(resultsPath, 'utf8');
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: results
              });
            }