name: Quiz Answer Validator
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  validate-quiz-answers:
    if: contains(github.event.pull_request.labels.*.name, 'check_theory')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to ensure we get all files

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Validate quiz answers
        id: validate
        run: |
          python .github/scripts/validate_quiz.py > quiz_summary.md
          cat quiz_summary.md

      - name: Upload validation report
        uses: actions/upload-artifact@v4
        with:
          name: quiz-validation-report
          path: quiz_summary.md