name: Quiz Answer Validator

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  validate-quiz-answers:
    if: contains(github.event.pull_request.labels.*.name, 'check_theory')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml markdown

      - name: Validate quiz answers
        id: validate
        run: |
          python .github/scripts/validate_quiz.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}